#
# 6502 assembler
#
#
#

require "./assembler"

module Assembler

  class C6502 < Assembler

    def decode_number (string)
      match("$[0-9A-F]+").as(:hex) >> (str(".w"))
      /$[0-9A-F]+\.B/i
      /[0-9]+/i
    end

    ARGUMENT_READERS = {
      "x" => {parse: value,
              emit: -> asm, str { asm.decode_number(str).to_i.if_within(-128, 255) }},
      "?" => {parse: value,
              emit: asm, str { asm.decode_number(str).to_i.if_within(-32768, 65535) }},
    }

    OPCODE_TYPES = [
      none: -> asm, bytecode, tokens { asm.db bytecode },
      bkpt: -> asm, bytecode, tokens { asm.breakpoint; asm.db bytecode },
      imm:  -> asm, bytecode, tokens { asm.db bytecode, tokens[0].b }
      bkpi: -> asm, bytecode, tokens { asm.breakpoint; asm.db bytecode, tokens[0].b }
      addr: -> asm, bytecode, tokens { asm.db bytecode, tokens[0].lo_byte, tokens[0].hi_byte },
      rel:  -> asm, bytecode, tokens { asm.db bytecode, tokens[0].relative_to(asm.here).b },
      bbit: -> asm, bytecode, tokens { asm.db bytecode, tokens[0].b, tokens[1].b }
    ]

    # adapted from the WLA-DX 6502 tables
    INSN_TABLE_6502 = [
      [[ "ADC #x",      0x69, :imm ]],
      [[ "ADC (x,X)",   0x61, :imm ]],
      [[ "ADC (x),Y",   0x71, :imm ]],
      [[ "ADC (x)",     0x72, :imm ]],
      [[ "ADC x,X",     0x75, :imm ],
       [ "ADC ?,X",     0x7D, :addr]],
      [[ "ADC ?,Y",     0x79, :addr]],
      [[ "ADC x",       0x65, :imm ],
       [ "ADC ?",       0x6D, :addr]],
      [[ "ADC.B #x",    0x69, :imm ]],
      [[ "ADC.B (x,X)", 0x61, :imm ]],
      [[ "ADC.B (x),Y", 0x71, :imm ]],
      [[ "ADC.B (x)",   0x72, :imm ]],
      [[ "ADC.B x,X",   0x75, :imm ]],
      [[ "ADC.W ?,X",   0x7D, :addr]],
      [[ "ADC.W ?,Y",   0x79, :addr]],
      [[ "ADC.B x",     0x65, :imm ]],
      [[ "ADC.W ?",     0x6D, :addr]],
      [[ "AND #x",      0x29, :imm ]],
      [[ "AND (x,X)",   0x21, :imm ]],
      [[ "AND (x),Y",   0x31, :imm ]],
      [[ "AND (x)",     0x32, :imm ]],
      [[ "AND x,X",     0x35, :imm ],
       [ "AND ?,X",     0x3D, :addr]],
      [[ "AND ?,Y",     0x39, :addr]],
      [[ "AND x",       0x25, :imm ],
       [ "AND ?",       0x2D, :addr]],
      [[ "AND.B #x",    0x29, :imm ]],
      [[ "AND.B (x,X)", 0x21, :imm ]],
      [[ "AND.B (x),Y", 0x31, :imm ]],
      [[ "AND.B (x)",   0x32, :imm ]],
      [[ "AND.B x,X",   0x35, :imm ]],
      [[ "AND.W ?,X",   0x3D, :addr]],
      [[ "AND.W ?,Y",   0x39, :addr]],
      [[ "AND.B x",     0x25, :imm ]],
      [[ "AND.W ?",     0x2D, :addr]],
      [[ "ASL A",       0x0A, :none]],
      [[ "ASL x,X",     0x16, :imm ],
       [ "ASL ?,X",     0x1E, :addr]],
      [[ "ASL x",       0x06, :imm ],
       [ "ASL ?",       0x0E, :addr]],
      [[ "ASL.B x,X",   0x16, :imm ]],
      [[ "ASL.W ?,X",   0x1E, :addr]],
      [[ "ASL.B x",     0x06, :imm ]],
      [[ "ASL.W ?",     0x0E, :addr]],
      [[ "ASL",         0x0A, :none]],
      [[ "BCC x",       0x90, :rel ]],
      [[ "BCS x",       0xB0, :rel ]],
      [[ "BEQ x",       0xF0, :rel ]],
      [[ "BMI x",       0x30, :rel ]],
      [[ "BNE x",       0xD0, :rel ]],
      [[ "BPL x",       0x10, :rel ]],
      [[ "BVC x",       0x50, :rel ]],
      [[ "BVS x",       0x70, :rel ]],
      [[ "BRA x",       0x80, :rel ]],
      [[ "BCC.B x",     0x90, :rel ]],
      [[ "BCS.B x",     0xB0, :rel ]],
      [[ "BEQ.B x",     0xF0, :rel ]],
      [[ "BMI.B x",     0x30, :rel ]],
      [[ "BNE.B x",     0xD0, :rel ]],
      [[ "BPL.B x",     0x10, :rel ]],
      [[ "BVC.B x",     0x50, :rel ]],
      [[ "BVS.B x",     0x70, :rel ]],
      [[ "BRA.B x",     0x80, :rel ]],
      [[ "BIT #x",      0x89, :imm ]],
      [[ "BIT x,X",     0x34, :imm ],
       [ "BIT ?,X",     0x3C, :addr]],
      [[ "BIT x",       0x24, :imm ],
       [ "BIT ?",       0x2C, :addr]],
      [[ "BIT.B x,X",   0x34, :imm ],
       [ "BIT.W ?,X",   0x3C, :addr]],
      [[ "BIT.B x",     0x24, :imm ],
       [ "BIT.W ?",     0x2C, :addr]],
      [[ "BRK x",       0x00, :bkpi]],
      [[ "BRK.B x",     0x00, :bkpi]],
      [[ "BRK",         0x00, :bkpt]],
      [[ "CLC",         0x18, :none]],
      [[ "CLD",         0xD8, :none]],
      [[ "CLI",         0x58, :none]],
      [[ "CLV",         0xB8, :none]],
      [[ "CMP #x",      0xC9, :imm ]],
      [[ "CMP (x,X)",   0xC1, :imm ]],
      [[ "CMP (x),Y",   0xD1, :imm ]],
      [[ "CMP (x)",     0xD2, :imm ]],
      [[ "CMP x,X",     0xD5, :imm ],
       [ "CMP ?,X",     0xDD, :addr]],
      [[ "CMP ?,Y",     0xD9, :addr]],
      [[ "CMP x",       0xC5, :imm ],
       [ "CMP ?",       0xCD, :addr]],
      [[ "CMP.B #x",    0xC9, :imm ]],
      [[ "CMP.B (x,X)", 0xC1, :imm ]],
      [[ "CMP.B (x),Y", 0xD1, :imm ]],
      [[ "CMP.B (x)",   0xD2, :imm ]],
      [[ "CMP.B x,X",   0xD5, :imm ]],
      [[ "CMP.W ?,X",   0xDD, :addr]],
      [[ "CMP.W ?,Y",   0xD9, :addr]],
      [[ "CMP.B x",     0xC5, :imm ]],
      [[ "CMP.W ?",     0xCD, :addr]],
      [[ "CPX #x",      0xE0, :imm ]],
      [[ "CPX x",       0xE4, :imm ],
       [ "CPX ?",       0xEC, :addr]],
      [[ "CPX.B #x",    0xE0, :imm ]],
      [[ "CPX.B x",     0xE4, :imm ]],
      [[ "CPX.W ?",     0xEC, :addr]],
      [[ "CPY #x",      0xC0, :imm ]],
      [[ "CPY x",       0xC4, :imm ],
       [ "CPY ?",       0xCC, :addr]],
      [[ "CPY.B #x",    0xC0, :imm ]],
      [[ "CPY.B x",     0xC4, :imm ]],
      [[ "CPY.W ?",     0xCC, :addr]],
      [[ "DEC x,X",     0xD6, :imm ],
       [ "DEC ?,X",     0xDE, :addr]],
      [[ "DEC x",       0xC6, :imm ],
       [ "DEC ?",       0xCE, :addr]],
      [[ "DEA",         0x3A, :none]],
      [[ "DEX",         0xCA, :none]],
      [[ "DEY",         0x88, :none]],
      [[ "DEC.B x,X",   0xD6, :imm ]],
      [[ "DEC.W ?,X",   0xDE, :addr]],
      [[ "DEC.B x",     0xC6, :imm ]],
      [[ "DEC.W ?",     0xCE, :addr]],
      [[ "EOR #x",      0x49, :imm ]],
      [[ "EOR (x,X)",   0x41, :imm ]],
      [[ "EOR (x),Y",   0x51, :imm ]],
      [[ "EOR (x)",     0x52, :imm ]],
      [[ "EOR x,X",     0x55, :imm ],
       [ "EOR ?,X",     0x5D, :addr]],
      [[ "EOR ?,Y",     0x59, :addr]],
      [[ "EOR x",       0x45, :imm ],
       [ "EOR ?",       0x4D, :addr]],
      [[ "EOR.B #x",    0x49, :imm ]],
      [[ "EOR.B (x,X)", 0x41, :imm ]],
      [[ "EOR.B (x),Y", 0x51, :imm ]],
      [[ "EOR.B (x)",   0x52, :imm ]],
      [[ "EOR.B x,X",   0x55, :imm ]],
      [[ "EOR.W ?,X",   0x5D, :addr]],
      [[ "EOR.W ?,Y",   0x59, :addr]],
      [[ "EOR.B x",     0x45, :imm ]],
      [[ "EOR.W ?",     0x4D, :addr]],
      [[ "INC x,X",     0xF6, :imm ],
       [ "INC ?,X",     0xFE, :addr]],
      [[ "INC x",       0xE6, :imm ],
       [ "INC ?",       0xEE, :addr]],
      [[ "INA",         0x1A, :none]],
      [[ "INX",         0xE8, :none]],
      [[ "INY",         0xC8, :none]],
      [[ "INC.B x,X",   0xF6, :imm ]],
      [[ "INC.W ?,X",   0xFE, :addr]],
      [[ "INC.B x",     0xE6, :imm ]],
      [[ "INC.W ?",     0xEE, :addr]],
      [[ "JMP (?,X)",   0x7C, :addr]],
      [[ "JMP (?)",     0x6C, :addr]],
      [[ "JMP ?",       0x4C, :addr]],
      [[ "JSR ?",       0x20, :addr]],
      [[ "JMP.W (?,X)", 0x7C, :addr]],
      [[ "JMP.W (?)",   0x6C, :addr]],
      [[ "JMP.W ?",     0x4C, :addr]],
      [[ "JSR.W ?",     0x20, :addr]],
      [[ "LDA #x",      0xA9, :imm ]],
      [[ "LDA (x,X)",   0xA1, :imm ]],
      [[ "LDA (x),Y",   0xB1, :imm ]],
      [[ "LDA (x)",     0xB2, :imm ]],
      [[ "LDA x,X",     0xB5, :imm ],
       [ "LDA ?,X",     0xBD, :addr]],
      [[ "LDA ?,Y",     0xB9, :addr]],
      [[ "LDA x",       0xA5, :imm ],
       [ "LDA ?",       0xAD, :addr]],
      [[ "LDA.B #x",    0xA9, :imm ]],
      [[ "LDA.B (x,X)", 0xA1, :imm ]],
      [[ "LDA.B (x),Y", 0xB1, :imm ]],
      [[ "LDA.B (x)",   0xB2, :imm ]],
      [[ "LDA.B x,X",   0xB5, :imm ]],
      [[ "LDA.W ?,X",   0xBD, :addr]],
      [[ "LDA.W ?,Y",   0xB9, :addr]],
      [[ "LDA.B x",     0xA5, :imm ]],
      [[ "LDA.W ?",     0xAD, :addr]],
      [[ "LDX #x",      0xA2, :imm ]],
      [[ "LDX x,Y",     0xB6, :imm ],
       [ "LDX ?,Y",     0xBE, :addr]],
      [[ "LDX x",       0xA6, :imm ],
       [ "LDX ?",       0xAE, :addr]],
      [[ "LDX.B #x",    0xA2, :imm ]],
      [[ "LDX.B x,Y",   0xB6, :imm ]],
      [[ "LDX.W ?,Y",   0xBE, :addr]],
      [[ "LDX.B x",     0xA6, :imm ]],
      [[ "LDX.W ?",     0xAE, :addr]],
      [[ "LDY #x",      0xA0, :imm ]],
      [[ "LDY x,X",     0xB4, :imm ],
       [ "LDY ?,X",     0xBC, :addr]],
      [[ "LDY x",       0xA4, :imm ],
       [ "LDY ?",       0xAC, :addr]],
      [[ "LDY.B #x",    0xA0, :imm ]],
      [[ "LDY.B x,X",   0xB4, :imm ]],
      [[ "LDY.W ?,X",   0xBC, :addr]],
      [[ "LDY.B x",     0xA4, :imm ]],
      [[ "LDY.W ?",     0xAC, :addr]],
      [[ "LSR A",       0x4A, :none]],
      [[ "LSR x,X",     0x56, :imm ],
       [ "LSR ?,X",     0x5E, :addr]],
      [[ "LSR x",       0x46, :imm ],
       [ "LSR ?",       0x4E, :addr]],
      [[ "LSR.B x,X",   0x56, :imm ]],
      [[ "LSR.W ?,X",   0x5E, :addr]],
      [[ "LSR.B x",     0x46, :imm ]],
      [[ "LSR.W ?",     0x4E, :addr]],
      [[ "LSR",         0x4A, :none]],
      [[ "NOP",         0xEA, :none]],
      [[ "ORA #x",      0x09, :imm ]],
      [[ "ORA (x,X)",   0x01, :imm ]],
      [[ "ORA (x),Y",   0x11, :imm ]],
      [[ "ORA (x)",     0x12, :imm ]],
      [[ "ORA x,X",     0x15, :imm ],
       [ "ORA ?,X",     0x1D, :addr]],
      [[ "ORA ?,Y",     0x19, :addr]],
      [[ "ORA x",       0x05, :imm ],
       [ "ORA ?",       0x0D, :addr]],
      [[ "ORA.B #x",    0x09, :imm ]],
      [[ "ORA.B (x,X)", 0x01, :imm ]],
      [[ "ORA.B (x),Y", 0x11, :imm ]],
      [[ "ORA.B (x)",   0x12, :imm ]],
      [[ "ORA.B x,X",   0x15, :imm ]],
      [[ "ORA.W ?,X",   0x1D, :addr]],
      [[ "ORA.W ?,Y",   0x19, :addr]],
      [[ "ORA.B x",     0x05, :imm ]],
      [[ "ORA.W ?",     0x0D, :addr]],
      [[ "PHA",         0x48, :none]],
      [[ "PHP",         0x08, :none]],
      [[ "PHX",         0xDA, :none]],
      [[ "PHY",         0x5A, :none]],
      [[ "PLA",         0x68, :none]],
      [[ "PLP",         0x28, :none]],
      [[ "PLX",         0xFA, :none]],
      [[ "PLY",         0x7A, :none]],
      [[ "ROL A",       0x2A, :none]],
      [[ "ROL x,X",     0x36, :imm ],
       [ "ROL ?,X",     0x3E, :addr]],
      [[ "ROL x",       0x26, :imm ],
       [ "ROL ?",       0x2E, :addr]],
      [[ "ROL.B x,X",   0x36, :imm ]],
      [[ "ROL.W ?,X",   0x3E, :addr]],
      [[ "ROL.B x",     0x26, :imm ]],
      [[ "ROL.W ?",     0x2E, :addr]],
      [[ "ROL",         0x2A, :none]],
      [[ "ROR A",       0x6A, :none]],
      [[ "ROR x,X",     0x76, :imm ],
       [ "ROR ?,X",     0x7E, :addr]],
      [[ "ROR x",       0x66, :imm ],
       [ "ROR ?",       0x6E, :addr]],
      [[ "ROR.B x,X",   0x76, :imm ]],
      [[ "ROR.W ?,X",   0x7E, :addr]],
      [[ "ROR.B x",     0x66, :imm ]],
      [[ "ROR.W ?",     0x6E, :addr]],
      [[ "ROR",         0x6A, :none]],
      [[ "RTI",         0x40, :none]],
      [[ "RTS",         0x60, :none]],
      [[ "SBC #x",      0xE9, :imm ]],
      [[ "SBC (x,X)",   0xE1, :imm ]],
      [[ "SBC (x),Y",   0xF1, :imm ]],
      [[ "SBC (x)",     0xF2, :imm ]],
      [[ "SBC x,X",     0xF5, :imm ],
       [ "SBC ?,X",     0xFD, :addr]],
      [[ "SBC ?,Y",     0xF9, :addr]],
      [[ "SBC x",       0xE5, :imm ],
       [ "SBC ?",       0xED, :addr]],
      [[ "SBC.B #x",    0xE9, :imm ]],
      [[ "SBC.B (x,X)", 0xE1, :imm ]],
      [[ "SBC.B (x),Y", 0xF1, :imm ]],
      [[ "SBC.B (x)",   0xF2, :imm ]],
      [[ "SBC.B x,X",   0xF5, :imm ]],
      [[ "SBC.W ?,X",   0xFD, :addr]],
      [[ "SBC.W ?,Y",   0xF9, :addr]],
      [[ "SBC.B x",     0xE5, :imm ]],
      [[ "SBC.W ?",     0xED, :addr]],
      [[ "SEC",         0x38, :none]],
      [[ "SED",         0xF8, :none]],
      [[ "SEI",         0x78, :none]],
      [[ "STA (x,X)",   0x81, :imm ]],
      [[ "STA (x),Y",   0x91, :imm ]],
      [[ "STA (x)",     0x92, :imm ]],
      [[ "STA x,X",     0x95, :imm ],
       [ "STA ?,X",     0x9D, :addr]],
      [[ "STA ?,Y",     0x99, :addr]],
      [[ "STA x",       0x85, :imm ],
       [ "STA ?",       0x8D, :addr]],
      [[ "STA.B (x,X)", 0x81, :imm ]],
      [[ "STA.B (x),Y", 0x91, :imm ]],
      [[ "STA.B (x)",   0x92, :imm ]],
      [[ "STA.B x,X",   0x95, :imm ]],
      [[ "STA.W ?,X",   0x9D, :addr]],
      [[ "STA.W ?,Y",   0x99, :addr]],
      [[ "STA.B x",     0x85, :imm ]],
      [[ "STA.W ?",     0x8D, :addr]],
      [[ "STX x,Y",     0x96, :imm ]],
      [[ "STX x",       0x86, :imm ],
       [ "STX ?",       0x8E, :addr]],
      [[ "STX.B x,Y",   0x96, :imm ]],
      [[ "STX.B x",     0x86, :imm ]],
      [[ "STX.W ?",     0x8E, :addr]],
      [[ "STY x,X",     0x94, :imm ]],
      [[ "STY x",       0x84, :imm ],
       [ "STY ?",       0x8C, :addr]],
      [[ "STY.B x,X",   0x94, :imm ]],
      [[ "STY.B x",     0x84, :imm ]],
      [[ "STY.W ?",     0x8C, :addr]],
      [[ "STZ x,X",     0x74, :imm ],
       [ "STZ ?,X",     0x9E, :addr]],
      [[ "STZ x",       0x64, :imm ],
       [ "STZ ?",       0x9C, :addr]],
      [[ "STZ.B x,X",   0x74, :imm ]],
      [[ "STZ.W x,X",   0x94, :addr]],
      [[ "STZ.B x",     0x64, :imm ]],
      [[ "STZ.W ?",     0x9C, :addr]],
      [[ "TAX",         0xAA, :none]],
      [[ "TAY",         0xA8, :none]],
      [[ "TSX",         0xBA, :none]],
      [[ "TXA",         0x8A, :none]],
      [[ "TXS",         0x9A, :none]],
      [[ "TYA",         0x98, :none]],
      [[ "TRB x",       0x14, :imm ],
       [ "TRB ?",       0x1C, :addr]],
      [[ "TRB.B x",     0x14, :imm ],
       [ "TRB.W ?",     0x1C, :addr]],

      [[ "TSB x",       0x04, :imm ],
       [ "TSB ?",       0x0C, :addr]],
      [[ "TSB.B x",     0x04, :imm ],
       [ "TSB.W ?",     0x0C, :addr]]
    ]

    OPCODE_TABLE_65C02 = OPCODE_TABLE_6502.insert(0,
        [[ "BBR0 x,x", 0x0F, :bbit]],
        [[ "BBR1 x,x", 0x1F, :bbit]],
        [[ "BBR2 x,x", 0x2F, :bbit]],
        [[ "BBR3 x,x", 0x3F, :bbit]],
        [[ "BBR4 x,x", 0x4F, :bbit]],
        [[ "BBR5 x,x", 0x5F, :bbit]],
        [[ "BBR6 x,x", 0x6F, :bbit]],
        [[ "BBR7 x,x", 0x7F, :bbit]],
        [[ "BBS0 x,x", 0x8F, :bbit]],
        [[ "BBS1 x,x", 0x9F, :bbit]],
        [[ "BBS2 x,x", 0xAF, :bbit]],
        [[ "BBS3 x,x", 0xBF, :bbit]],
        [[ "BBS4 x,x", 0xCF, :bbit]],
        [[ "BBS5 x,x", 0xDF, :bbit]],
        [[ "BBS6 x,x", 0xEF, :bbit]],
        [[ "BBS7 x,x", 0xFF, :bbit]],
        [[ "RMB0 x",   0x07, :imm ]],
        [[ "RMB1 x",   0x17, :imm ]],
        [[ "RMB2 x",   0x27, :imm ]],
        [[ "RMB3 x",   0x37, :imm ]],
        [[ "RMB4 x",   0x47, :imm ]],
        [[ "RMB5 x",   0x57, :imm ]],
        [[ "RMB6 x",   0x67, :imm ]],
        [[ "RMB7 x",   0x77, :imm ]],
        [[ "SMB0 x",   0x87, :imm ]],
        [[ "SMB1 x",   0x97, :imm ]],
        [[ "SMB2 x",   0xA7, :imm ]],
        [[ "SMB3 x",   0xB7, :imm ]],
        [[ "SMB4 x",   0xC7, :imm ]],
        [[ "SMB5 x",   0xD7, :imm ]],
        [[ "SMB6 x",   0xE7, :imm ]],
        [[ "SMB7 x",   0xF7, :imm ]]
      )
  end
end